"use client";

import Sidenav from "@/components/Sidenav";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import axios, { AxiosError } from "axios";
import { useState, useEffect, useLayoutEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { getUser } from "@/utils";
import { SidenavProvider, useSidenav } from "@/context/SideNavContext";
import TopBar from "@/components/TopBar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isSuccess, setIsSuccess] = useState<boolean>(false);
  const { push } = useRouter();
  useLayoutEffect(() => {
    (async () => {
      const { user, error } = await getUser();

      if (!user) {
        push("/auth/login");
        return;
      }

      setIsSuccess(true);
    })();
  }, [push]);


  return (
    <SidenavProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="flex flex-row bg-gradient-to-b from-[#F7FCFF] p-6 md:p-0">
            {/* <aside className={`hidden md:w-[16rem] md:block`}> */}
              <Sidenav />
            {/* </aside> */}

            {/** max-md:pb-32 */}
            <section className="w-full min-h-screen flex-col items-center sm:px-2 md:w-[calc(100vw-16rem)]">
              {" "}
              <TopBar />
              {children}
            </section>
          </main>
        </body>
      </html>
    </SidenavProvider>
  );
}
